In [1]:
import numpy as np

In [5]:
table = np.asarray([[1, 0, 0, 0],
                   [1, 0, 1, 0],
                   [1, 1, 0, 0],
                   [1, 1, 1, 1]])

W = np.asarray([[2, 2, 2]])

for i in range(10):
    for j in range(4):
        if W.dot(table[j, :][0:3].T) >= 0 and table[j, 3] == 0:
            W = W - table[j, 0:3]
        elif W.dot(table[j, :][0:3].T) <= 0 and table[j, 3] == 1:
            W = W + table[j, 0:3]
        print(W)

[[1 2 2]]
[[0 2 1]]
[[-1  1  1]]
[[-1  1  1]]
[[-1  1  1]]
[[-2  1  0]]
[[-2  1  0]]
[[-1  2  1]]
[[-1  2  1]]
[[-2  2  0]]
[[-3  1  0]]
[[-2  2  1]]
[[-2  2  1]]
[[-2  2  1]]
[[-3  1  1]]
[[-2  2  2]]
[[-2  2  2]]
[[-3  2  1]]
[[-3  2  1]]
[[-2  3  2]]
[[-2  3  2]]
[[-3  3  1]]
[[-4  2  1]]
[[-3  3  2]]
[[-3  3  2]]
[[-3  3  2]]
[[-4  2  2]]
[[-3  3  3]]
[[-3  3  3]]
[[-4  3  2]]
[[-4  3  2]]
[[-4  3  2]]
[[-4  3  2]]
[[-4  3  2]]
[[-4  3  2]]
[[-4  3  2]]
[[-4  3  2]]
[[-4  3  2]]
[[-4  3  2]]
[[-4  3  2]]
